create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  detail text not null default 'Small-batch ceramic',
  price numeric(10, 2) not null check (price >= 0),
  image text,
  tone text not null default 'clay' check (tone in ('clay', 'sage', 'sky')),
  created_at timestamptz not null default now()
);

alter table public.products enable row level security;

drop policy if exists "Products are public" on public.products;
create policy "Products are public" on public.products for select using (true);

insert into public.products (name, detail, price, tone)
select * from (values
  ('Sunday Morning', 'Hand-painted ceramic', 399.00, 'clay'),
  ('Daily Ritual', 'Stoneware coffee cup', 449.00, 'sage'),
  ('Good Things', 'Limited quote series', 499.00, 'sky')
) as seed(name, detail, price, tone)
where not exists (select 1 from public.products);